
on: 
  push: 

name: continuous integration

jobs: 
  build: 
    name: Build file 
    runs-on: ubuntu-latest
    steps:
      - name: print lean and lake versions
        run: |
          lean --version
          lake --version

