on: 
  push: 
    branches: 
      - master

jobs: 
  build_docs: 
    name: build docs
    runs-on: ubuntu-latest
    steps: 

      - uses: actions/checkout@v4

      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
          ~/.elan/bin/lean --version
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      
      - name: build cache
        run: |
         lake build cache
      
      - name: build the docs
        run: |
          mkdir -p .lake/build/doc
          lake -R -Kenv=dev build AnomalyCancellationInLean:docs
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages 
          folder: ./.lake/build/doc
 